version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: scheduler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: scheduler-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disables password requirement for local dev
      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Caps RAM usage so it doesn't crash your PC
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  redis_data:
  es_data: